========================================================
### Multivariate Data

```{r Third Qualitative Variable}
library(ggplot2)
pf <- read.delim('../lesson3/pseudo_facebook.tsv')
ggplot(aes(x = age, y = friend_count), data = pf) +
  geom_point()

qplot(x = age, y = friend_count, data = pf)
qplot(age, friend_count, data = pf)

```

***

### Plotting Conditional Summaries
Notes:

```{r Plotting Conditional Summaries}
summary(pf$age)
ggplot(aes(x = age, y = friend_count), data = pf) +
  geom_point(alpha = 1/20, position = position_jitter(h = 0)) + xlim(13,90)+coord_trans(y = "sqrt")
```
***

### Conditional means
```{r}
install.packages('dplyr')
library(dplyr)
pf.fc_by_age <- pf %>%
  group_by(age) %>%
  summarise(friend_count_mean = mean(friend_count),
            friend_count_median = median(friend_count),
            n = n()) %>%
  arrange(age)

head(pf.fc_by_age, 20)

ggplot(aes(x = age, y = friend_count_mean), data = pf.fc_by_age) +
  geom_line() + xlim(13,90)+coord_trans(y = "sqrt")
```

### Overlayng summaries
```{r}
ggplot(aes(x = age, y = friend_count), data = pf) +
  geom_point(alpha = 1/20, position = position_jitter(h = 0), color = 'orange') + xlim(13,90)+coord_trans(y = "sqrt") +
  geom_line(stat = 'summary', fun.y = mean)+
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = .1), linetype = 2, color = 'blue') +
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = .5), color = 'blue') +
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = .9), linetype = 2, color = 'blue')
```
***

### Correlation
```{r}
cor.test(pf$age, pf$friend_count, method = 'pearson')
with(pf, cor.test(age, friend_count, method = 'pearson'))
with(subset(pf, pf$age <= 70), cor.test(age, friend_count, method = 'pearson'))
```
***

### Likes
```{r}
ggplot(aes(x = www_likes_received, y = likes_received), data = pf) +
  geom_point(alpha = 1/20)+xlim(0, quantile(pf$www_likes_received, .95))+ylim(0, quantile(pf$likes_received, .95))+
  geom_smooth(method= 'lm',color ='red')

with(pf, cor.test(www_likes_received, likes_received, method = 'pearson'))

```

### Age with month
```{r}
ggplot(aes(x = age, y = friend_count_mean), data = pf.fc_by_age) +
  geom_line()

pf$age_with_months <- pf$age + (1 - round(pf$dob_month / 12,3))
head(pf$age_with_months)

pf$age_with_months <-pf$age + (1 - pf$dob_month / 12)
pf.fc_by_age_months <- pf %>%
  group_by(age_with_months) %>%
  summarise(friend_count_mean = mean(friend_count),
            friend_count_median = median(friend_count),
            n = n()) %>%
  arrange(age_with_months)

head(pf.fc_by_age_months)

ggplot(aes(x = age_with_months, y = friend_count_mean), data = subset(pf.fc_by_age_months, pf.fc_by_age_months$age_with_months < 71)) +
  geom_line()+ geom_smooth()
```
